security:
    password_hashers:
        App\Entity\User:
            algorithm: auto


    providers:
        # used to reload user from session & other features (e.g. switch_user)
        app_user_provider:
            entity:
                class: App\Entity\User
                property: email

    firewalls:
        main:
            form_login:
                login_path: app_login
                check_path: app_login
            logout:
                path: app_logout
                target: /


    access_control:
        - { path: ^/login, roles: PUBLIC_ACCESS }

        - { path: ^/$, roles: PUBLIC_ACCESS }
        - { path: ^/comments/new$, roles: PUBLIC_ACCESS }
        - { path: ^/.*/\d+$, roles: PUBLIC_ACCESS } # Pour show

        - { path: ^/comments/\d+/edit$, roles: IS_AUTHENTICATED_FULLY }
        - { path: ^/comments/\d+/delete$, roles: IS_AUTHENTICATED_FULLY }

        - { path: ^/tasks, roles: IS_AUTHENTICATED_FULLY }
        - { path: ^/tasks/new$, roles: IS_AUTHENTICATED_FULLY }
        - { path: ^/tasks/\d+/edit$, roles: IS_AUTHENTICATED_FULLY }
        - { path: ^/tasks/\d+/delete$, roles: IS_AUTHENTICATED_FULLY }
        - { path: ^/tasks/\d+$, roles: IS_AUTHENTICATED_FULLY } # Pour show

        # Règles pour les services
        - { path: ^/services/new$, roles: [ROLE_ADMIN, ROLE_EMPLOYEE] }
        - { path: ^/services/\d+/edit$, roles: [ROLE_ADMIN, ROLE_EMPLOYEE] }
        - { path: ^/services/\d+/delete$, roles: [ROLE_ADMIN, ROLE_EMPLOYEE] }
        - { path: ^/services/\d+$, roles: [ROLE_ADMIN, ROLE_EMPLOYEE] } # Exemple pour show

        # Règles générales pour toutes les autres routes
        - { path: ^/.*/new$, roles: ROLE_ADMIN }
        - { path: ^/.*/\d+/edit$, roles: ROLE_ADMIN }
        - { path: ^/.*/\d+/delete$, roles: ROLE_ADMIN }
        - { path: ^/.*/\d+$, roles: ROLE_ADMIN } # Exemple pour show

        - { path: ^/profile, roles: IS_AUTHENTICATED_FULLY }
        - { path: ^/register, roles: ROLE_ADMIN }
        - { path: ^/admin, roles: ROLE_ADMIN }
        - { path: ^/role, roles: ROLE_ADMIN }



when@test:
    security:
        password_hashers:
            # By default, password hashers are resource intensive and take time. This is
            # important to generate secure password hashes. In tests however, secure hashes
            # are not important, waste resources and increase test times. The following
            # reduces the work factor to the lowest possible values.
            Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface:
                algorithm: auto
                cost: 4 # Lowest possible value for bcrypt
                time_cost: 3 # Lowest possible value for argon
                memory_cost: 10 # Lowest possible value for argon
