controllers:
    resource: 
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute

frontend:
    path: /{reactRouting}
    controller: App\Controller\HomeController::index
    defaults:
        reactRouting: null
    requirements:
        reactRouting: .*
